sudo: false
language: java

dist:
  - trusty

before_cache:
  # No sense in caching current build artifacts
  - rm -rf $HOME/.m2/repository/com/zaxxer

cache:
  directories:
    - $HOME/.m2/repository

install: /bin/true

jdk: openjdk11

script:
  - mvn package -Dmaven.javadoc.skip=true -V -B

after_success:
  - bash <(curl -s https://codecov.io/bash)
